course/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url


app_name = 'shopping_cart'

urlpatterns = [
    path('',newcourse,name='coursepaid'),
    path('allclasses/',allcourse,name='allcourse'),
    path('courseview/<int:myid>',productView,name='productview'),
]

lms/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',indexshow,name='indexshow'),
    path('contact/',contact,name='contact'),
    path('team/',team,name='team'),
    path('about/',about,name='about'),
]

student_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from authy.views import UserProfile
from classroom.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('authy.urls')),
    path('', include('course.urls')),
    path('course/', include('classroom.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('direct/', include('direct.urls')),
    path('<username>', UserProfile, name='profile'),
    path('class/', index, name='index'),
    path('bye/',include('lms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_portal/templates/temp/snipest/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
        <meta charset="utf-8">
        <title>Learing Portal- LMS</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href="{% static '' %}img/favicon.ico" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static '' %}temp/lib/animate/animate.min.css" rel="stylesheet">
        <link href="{% static '' %}temp/lib/flaticon/font/flaticon.css" rel="stylesheet">
        <link href="{% static '' %}temp/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="{% static '' %}temp/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

        <!-- Template Stylesheet -->
{#        <link href="{% static 'student/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>#}
{#        <link href="{% static 'student/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>#}
        <link href="{% static '' %}temp/css/style.css" rel="stylesheet">
        {% block css %}

        {% endblock css %}
    </head>

<body>
        <!-- Top Bar Start -->
        <div class="top-bar d-none d-md-block">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <div class="top-bar-left">
                            <div class="text">
                                <i class="far fa-clock"></i>
                                <h2>8:00 - 9:00</h2>
                                <p>Mon - Fri</p>
                            </div>
                            <div class="text">
                                <i class="fa fa-phone-alt"></i>
                                <h2>+923 0604 93989</h2>
                                <p>For Other Info</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="top-bar-right">
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a href="/" class="navbar-brand">Learing <span>Portal</span></a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="/" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'shopping_cart:allcourse' %}" class="nav-item nav-link">Lecture</a>
                        <a href="{% url 'team' %}" class="nav-item nav-link">Teacher</a>
                        <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
                        {% if user.is_authenticated %}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ user.username }}</a>
                                <div class="dropdown-menu">
                                    <a href="" class="dropdown-item">Profile</a>
                                    <a href="{% url 'index' %}" class="dropdown-item">Dashboard</a>
                                    <a href="{% url 'inbox' %}" class="dropdown-item">Inbox{% if directs_count %}<span class="new badge red">{{ directs_count }}</span>{% endif %}</a>
                                    <a href="{% url 'logout' %}" class="dropdown-item">LogOut</a>
                                </div>
                            </div>
                            {% else %}
                        <a href="{% url 'login' %}" class="nav-item nav-link">Login/Signup</a>
                        {% endif %}
                </div>
                    </div>
            </div>
        </div>
        <!-- Nav Bar End -->
        {% block contentbase %}

        {% endblock contentbase %}


        <!-- Footer Start -->
        <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <a href="{% url 'indexshow' %}" class="footer-logo">Learing <span>Portal</span> - LMS</a>
                        <h3>Model Town Lahore</h3>
                        <div class="footer-menu">
                            <p>+923 0604 93989</p>
                            <p>abtechsol09@gmail.com</p>
                        </div>
                        <div class="footer-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <div class="row">
                        <div class="col-md-6">
                            <p>&copy; <a target="_blank" href="https://techsol.herokuapp.com/">TechSol</a>, All Right Reserved.</p>
                        </div>
                        <div class="col-md-6">
                            <p>Designed By <a target="_blank" href="https://techsol.herokuapp.com/">TechSol</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static '' %}temp/lib/easing/easing.min.js"></script>
        <script src="{% static '' %}temp/lib/wow/wow.min.js"></script>
        <script src="{% static '' %}temp/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="{% static '' %}temp/lib/isotope/isotope.pkgd.min.js"></script>
        <script src="{% static '' %}temp/lib/lightbox/js/lightbox.min.js"></script>

        <!-- Contact Javascript File -->
        <script src="{% static '' %}temp/mail/jqBootstrapValidation.min.js"></script>
        <script src="{% static '' %}temp/mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="{% static '' %}temp/js/main.js"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    {% block js %}

    {% endblock js %}
    </body>

</html>

student_portal/templates/temp/snipest/discount.html
{% load static %}
<!-- Discount Start -->
<div class="discount wow zoomIn" data-wow-delay="0.1s" style="margin-bottom: 90px;">
            <div class="container">
                <div class="section-header text-center">
                    <p>Awesome Discount</p>
                    <h2>Get <span>30%</span> Discount for all Classes</h2>
                </div>
                <div class="container discount-text">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus.
                    </p>
                    <a class="btn">Join Now</a>
                </div>
            </div>
        </div>
<!-- Discount End -->

student_portal/templates/temp/snipest/price.html
{% load static %}

<!-- Price Start -->
<div class="price">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>Online Package</p>
                    <h2>Online Pricing Plan</h2>
                </div>
                <div class="row">
                    {% for i in price %}
                    <div class="col-md-4 wow fadeInUp" data-wow-delay="0.3s">
                        <div class="price-item">
                            <div class="price-header">
                                <div class="price-title">
                                    <h2>{{i.pakg}}</h2>
                                </div>
                                <div class="price-prices">
                                    <h2><small>$</small>{{i.price}}<span>/ mo</span></h2>
                                </div>
                            </div>
                            <div class="price-body">
                                <div class="price-description">
                                    <ul>
                                        <li>{{i.foffere}}</li>
                                        <li>{{ i.soffere }}</li>
                                        <li>{{ i.toffere }}</li>
                                        <li>{{ i.fouoffere }}</li>
                                        <li>{{ i.fivoffere }}</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="price-footer">
                                <div class="price-action">
                                    <a class="btn" href="">Join Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
<!-- Price End -->

student_portal/templates/temp/snipest/team.html
{% load static %}

<!-- Team Start -->
<div class="team">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>Teacher</p>
                    <h2>Expert Teacher,Trainer</h2>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.0s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static '' %}temp/img/team-1.jpg" alt="Image">
                                <div class="team-social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                            <div class="team-text">
                                <h2>Millie Harper</h2>
                                <p>Coding Teacher</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static '' %}temp/img/team-3.jpg" alt="Image">
                                <div class="team-social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                            <div class="team-text">
                                <h2>Lilly Fry</h2>
                                <p>Account Teacher</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static '' %}temp/img/team-1.jpg" alt="Image">
                                <div class="team-social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                            <div class="team-text">
                                <h2>Elise Moran</h2>
                                <p>Marketing Teacher</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static '' %}temp/img/team-2.jpg" alt="Image">
                                <div class="team-social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                            <div class="team-text">
                                <h2>Elise Moran</h2>
                                <p>Fashion Teacher</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!-- Team End -->